### ISSUE TITLE
Binary Not Downloadable

### ISSUE THREAD

**Issue by DerAlo** [ThaCheeseBun/pwngps#1]
Hey hey;) Very cool Project and a Must for Pwnagotchi lovers:) 
Thank U for ur effort.
I'd Love to use it, but unfortunatly the binary ist Not available at https://github.com/ThaCheeseBun/pwngps/releases/download/latest/pwngps-aarch64

Unfortunatly im too stupid for Compiling the Rust source, due Zero Rust knowledge;( 

Would be cool If U fix the Link/build/binary :)

Thx in advance, a Pwnagotchi friend

Edit:
Nevermind - im an idiot..  only "latest" wasnt found .. https://github.com/ThaCheeseBun/pwngps/releases/download/v0.1.0/pwngps-aarch64  works

**Comment by ThaCheeseBun** [comment]
Yo.
Nice that you found it yourself! It seems like GitHub changed something and I just need to switch "download" and "latest" in the URL. It has definitely worked before 🤷. Thanks for pointing it out, will fix.
Btw, please provide feedback on how it works. I don't have much time to test it myself (I don't even have access to the device at all right now) so it would be appreciated :).
