### ISSUE TITLE
Missing field Latitude

### ISSUE THREAD

**Issue by DerAlo** [ThaCheeseBun/pwngps#3]
Hey ;)

As you wished to have some feedback - here we go ;P

Im using a Pixel 6 (CPU: 2x 2.8 GHz Cortex-X1, 2x 2.25 GHz Cortex-A76, 4x 1.8 GHz Cortex-A55  from chip designer Arm)

To be able to say "i tried both scripts - for armv7 & aarch64" - i did so^^

Unfortunately it doesnt seem like my pwnagotchis pawngps plugin is calling 192.168.44.44:42069 via bluetooth (general functionality is proofen by OHC  & wpa-sec uploads - and Termux wakelock is aquired ), so im triggering it via browser on the phone (http://127.0.0.1:42069/api/v1/gps).

This browser http get leeds to the error in this picture:
![image](https://github.com/ThaCheeseBun/pwngps/assets/34653127/cca7de5b-aa45-40e8-b399-a68e15c2bd55)

Thats how far i came ^^  The error "Missing field Latitude" makes me curious - perhaps the script isnt able to obtain gps data from the android location provider?
Despite that im not able to say if cpu architecture is a thing.. and of course i'd be happy for suggestions why the paw-gps plugin isnt trying to connect at handshake capturing.

So once again thank u for ur effort - i was already in the mood to code and release a native android gps-server app  before  finding your project^^

**Comment by ThaCheeseBun** [comment]
Yo
Sorry for not responding to this, must have gotten lost in my inbox while i was migrating to my new mail.
Bit the bullet and decided to create an actual app for this instead. So if you are still interested in this go give that project a try instead [https://github.com/ThaCheeseBun/PwnGPS-app](https://github.com/ThaCheeseBun/PwnGPS-app).
It's currently very early alpha but should still be more stable and consistent than this project will ever be.
